/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import controler.Controller;

import domen.Grad;
import domen.Prenociste;
import domen.Referent;
import domen.StudenskiDom;
import domen.Student;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.SealedObject;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;
import models.JtxtListener;
import models.PrenocisteModelPrikaz;

import sesion.Sesion;

/**
 *
 * @author Stefan
 */


public class FNew extends javax.swing.JDialog {

    /**
     * Creates new form FNew
     */
    private PrenocisteModelPrikaz pmp;
    private Student student;
    public FNew(java.awt.Frame parent, boolean modal, Student st) throws SQLException, Exception {
        
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        populateCombo();
        setStatusBar();
        this.student=st;

        pripremiforumuforView(st);
        
          List<Prenociste> listaPrenocista=Controller.vratiListuPrenocistaZaOdredjenogReferentaIStudenta(st);
          st.setPrenocista(listaPrenocista);
         
          for (Prenociste prenociste : listaPrenocista) {
              System.out.println(prenociste.getGost().getIme());
        }
          pmp=new PrenocisteModelPrikaz(listaPrenocista);
          jTable1.setModel(pmp);
          jTable1.setVisible(true);
        
       
    }

    public FNew(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        populateCombo();
        setStatusBar();

        obaveznapolja();
        pripremizapregled(FormMode.New);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtPrezime = new javax.swing.JTextField();
        JTxtJMBG = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtBrojCipKartice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboGrad = new javax.swing.JComboBox<>();
        jbtnZapamti = new javax.swing.JButton();
        jPanelObavezno = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        obavezno = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtnPromeni = new javax.swing.JButton();
        jbtnSacuvajPromenu = new javax.swing.JButton();
        jbtnIzadji = new javax.swing.JButton();
        jbtnObrisi = new javax.swing.JButton();
        jPanelTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos Studenta");

        jLabel1.setText("Ime:");

        jtxtIme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtImeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtImeKeyReleased(evt);
            }
        });

        jLabel2.setText("Prezime:");

        JTxtJMBG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JTxtJMBGMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JTxtJMBGMouseExited(evt);
            }
        });

        jLabel3.setText("JMBG:");

        jLabel4.setText("Broj Cip Kartice:");

        jLabel5.setText("Grad:");

        jbtnZapamti.setText("Zapamti");
        jbtnZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnZapamtiActionPerformed(evt);
            }
        });

        jLabel6.setText("Polja oznacena sa ");

        jLabel7.setText("su obavezna");

        javax.swing.GroupLayout jPanelObaveznoLayout = new javax.swing.GroupLayout(jPanelObavezno);
        jPanelObavezno.setLayout(jPanelObaveznoLayout);
        jPanelObaveznoLayout.setHorizontalGroup(
            jPanelObaveznoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelObaveznoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(obavezno, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(39, 39, 39))
        );
        jPanelObaveznoLayout.setVerticalGroup(
            jPanelObaveznoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelObaveznoLayout.createSequentialGroup()
                .addGroup(jPanelObaveznoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelObaveznoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanelObaveznoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(obavezno, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelObaveznoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jbtnPromeni.setText("Promeni");
        jbtnPromeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPromeniActionPerformed(evt);
            }
        });

        jbtnSacuvajPromenu.setText("Sacuvaj Promenu");
        jbtnSacuvajPromenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajPromenuActionPerformed(evt);
            }
        });

        jbtnIzadji.setText("Izadji");
        jbtnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzadjiActionPerformed(evt);
            }
        });

        jbtnObrisi.setText("Obrisi");
        jbtnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setText("Prenocista koja je student prijavio u tekucem mesecu");

        javax.swing.GroupLayout jPanelTabelaLayout = new javax.swing.GroupLayout(jPanelTabela);
        jPanelTabela.setLayout(jPanelTabelaLayout);
        jPanelTabelaLayout.setHorizontalGroup(
            jPanelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanelTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTabelaLayout.setVerticalGroup(
            jPanelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(85, 85, 85))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboGrad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtxtBrojCipKartice, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTxtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jtxtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelObavezno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jbtnZapamti)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(jbtnIzadji)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnSacuvajPromenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnPromeni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTxtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBrojCipKartice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jPanelObavezno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jbtnZapamti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPromeni)
                    .addComponent(jbtnSacuvajPromenu)
                    .addComponent(jbtnIzadji)
                    .addComponent(jbtnObrisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnZapamtiActionPerformed

        if (validacija()) {
            String ime = jtxtIme.getText().trim();
            String prezime = jtxtPrezime.getText().trim();
            String jmbg = JTxtJMBG.getText().trim();
            String brciop = jtxtBrojCipKartice.getText().trim();
            Grad g = (Grad) jComboGrad.getSelectedItem();
            Referent ulogovani = (Referent) Sesion.getInstance().getMap().get("ulogovani");
            try {
                StudenskiDom sd = Controller.vratiDomZaODrjedjenogRefernta(ulogovani);
                Student s = new Student(jmbg, brciop, ime, prezime, sd, g);
                
                Controller.zapamtiStudenta(s);
               
                JOptionPane.showMessageDialog(null, "Sistem je uspesno zapamtio studenta");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Sistem ne moze da zapamti studenta");
                Logger.getLogger(FNew.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(FNew.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbtnZapamtiActionPerformed

    private void JTxtJMBGMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTxtJMBGMouseEntered

    }//GEN-LAST:event_JTxtJMBGMouseEntered

    private void JTxtJMBGMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTxtJMBGMouseExited

    }//GEN-LAST:event_JTxtJMBGMouseExited

    private void jtxtImeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtImeKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtxtImeKeyPressed

    private void jtxtImeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtImeKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jtxtImeKeyReleased

    private void jbtnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzadjiActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnIzadjiActionPerformed

    private void jbtnPromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPromeniActionPerformed
        try {
            pripremizapregled(FormMode.Edit);
        } catch (Exception ex) {
            Logger.getLogger(FNew.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnPromeniActionPerformed

    private void jbtnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiActionPerformed
       
       // Student s=(Student)Sesion.getInstance().getMap().get("student");
        try {
            
           
            Controller.ObrisiStudenta(student);
            
            JOptionPane.showMessageDialog(null, "Uspesno je obrisan student sa id: "+student.getStudentID());
           
            //Sesion.getInstance().getMap().remove("student");
            dispose();
            
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, "Nije moguce obrisati izabranog studenta");
        }
        
    }//GEN-LAST:event_jbtnObrisiActionPerformed

    private void jbtnSacuvajPromenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajPromenuActionPerformed
       
        try {
           if(validacija()==true){
                
                     
            student.setIme(jtxtIme.getText().trim());
            student.setPrezime(jtxtPrezime.getText().trim());
            student.setJMBG(JTxtJMBG.getText().trim());
            student.setBrojCipKartice(jtxtBrojCipKartice.getText().trim());
            student.setGrad((Grad)jComboGrad.getSelectedItem());
            
            
          
            Controller.promeniStudenta(student);
            JOptionPane.showMessageDialog(null, "Uspoesno je izmenjen student sa id:" +student.getStudentID());
            
           dispose();
          
           }
            
            
        } catch (Exception ex) {
            Logger.getLogger(FNew.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnSacuvajPromenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTxtJMBG;
    private javax.swing.JComboBox<Object> jComboGrad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelObavezno;
    private javax.swing.JPanel jPanelTabela;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnIzadji;
    private javax.swing.JButton jbtnObrisi;
    private javax.swing.JButton jbtnPromeni;
    private javax.swing.JButton jbtnSacuvajPromenu;
    private javax.swing.JButton jbtnZapamti;
    private javax.swing.JTextField jtxtBrojCipKartice;
    private javax.swing.JTextField jtxtIme;
    private javax.swing.JTextField jtxtPrezime;
    private javax.swing.JLabel obavezno;
    // End of variables declaration//GEN-END:variables

    private void populateCombo() throws  Exception {

        List<Grad> gradovi = Controller.vratiSveGradove();
        jComboGrad.removeAllItems();
        for (Grad grad : gradovi) {
            jComboGrad.addItem(grad);
        }
    }

    private boolean validacija() {
        if (jtxtIme.getText().isEmpty() || jtxtPrezime.getText().isEmpty() || JTxtJMBG.getText().isEmpty() || jtxtBrojCipKartice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Sva polja moraju biti popunjena");
            return false;
        }
        if (JTxtJMBG.getText().length() != 13) {
            JOptionPane.showMessageDialog(null, "JMBG mora sadrzati 13 cifara");
            return false;
        }
        try {
            
            Long lon=Long.parseLong(JTxtJMBG.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "JMBG se mora sastojati od cifara");
            return false;
        }
        if (jtxtBrojCipKartice.getText().length() != 9) {
            JOptionPane.showMessageDialog(null, "Cip kartica mora sadrazti 9 cifara");
            return false;
        }
        try {
            int cip = Integer.parseInt(jtxtBrojCipKartice.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cip kartica se mora sastojati od cifara");
            return false;
        }
       

        return true;
    }

    JLabel statusLabel;
    JPanel statusPanel;

    private void setStatusBar() {
        setLayout(new BorderLayout());

        statusPanel = new JPanel();
        statusPanel.setBorder(new BevelBorder(BevelBorder.LOWERED));
        add(statusPanel, BorderLayout.SOUTH);

        statusPanel.setPreferredSize(new Dimension(getWidth(), 30));
        statusPanel.setLayout(new BoxLayout(statusPanel, BoxLayout.X_AXIS));
        Referent r = (Referent) Sesion.getInstance().getMap().get("ulogovani");
        statusLabel = new JLabel("Trenutno ulogovani referent:" + r.getIme() + " " + r.getPrezime());

        statusPanel.add(statusLabel);
    }

    private void pripremiforumuforView(Student s) throws Exception {
        
        pripremizapregled(FormMode.View);
        jtxtIme.setText(s.getIme());
        jtxtPrezime.setText(s.getPrezime());
        JTxtJMBG.setText(s.getJMBG());
        jtxtBrojCipKartice.setText(s.getBrojCipKartice());
        jComboGrad.setSelectedItem(s.getGrad());

    }

    private void obaveznapolja() throws Exception {
        new JtxtListener(jtxtIme);
        new JtxtListener(jtxtPrezime);
        new JtxtListener(jtxtBrojCipKartice);
        new JtxtListener(JTxtJMBG);
        obavezno.setBorder(BorderFactory.createLineBorder(Color.RED));
        Referent referent = (Referent) Sesion.getInstance().getMap().get("ulogovani");
        StudenskiDom dom = Controller.vratiDomZaODrjedjenogRefernta(referent);
        this.setTitle("Studenski dom: " + dom.getNaziv());
        
    }

    private void pripremizapregled(FormMode formMode) throws Exception {
        switch (formMode) {
            case View:
                jtxtIme.setEnabled(false);
                jtxtBrojCipKartice.setEnabled(false);
                JTxtJMBG.setEnabled(false);
                jtxtPrezime.setEnabled(false);
                jComboGrad.setEnabled(false);
                jPanelObavezno.setVisible(false);
                
               
                jbtnZapamti.setVisible(false);
                jbtnSacuvajPromenu.setEnabled(false);
                jPanelTabela.setVisible(true);

                break;
            case New:
                
                jbtnPromeni.setVisible(false);
                jbtnSacuvajPromenu.setVisible(false);
                jbtnObrisi.setVisible(false);
                jPanelTabela.setVisible(false);
                
                break;
            case Edit:
                jbtnPromeni.setEnabled(false);
                jbtnSacuvajPromenu.setEnabled(true);
                
                
                
                 jtxtIme.setEnabled(true);
                jtxtBrojCipKartice.setEnabled(true);
                JTxtJMBG.setEnabled(true);
                jtxtPrezime.setEnabled(true);
                jComboGrad.setEnabled(true);
                jbtnObrisi.setVisible(false);
                jPanelTabela.setVisible(true);
                
                obaveznapolja();
                
                break;
        }

    }

}
