/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import controler.Controller;

import domen.Prenociste;
import domen.Referent;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import models.PrenocisteModelPrikaz;
import sesion.Sesion;

/**
 *
 * @author Stefan
 */
public class FPretragaPrenocista extends javax.swing.JFrame {

    /**
     * Creates new form FPretragaPrenocista
     */
    PrenocisteModelPrikaz pmp;
    public FPretragaPrenocista() throws Exception {
        initComponents();
        podesiTabelu();
        setLocationRelativeTo(null);
        
       
        
        setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtPretragaPrenocista = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPrenocista = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretraga prenocista"));

        jLabel1.setText("Unesite kriterijum za pretragu:");

        jtxtPretragaPrenocista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPretragaPrenocistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jtxtPretragaPrenocista)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtPretragaPrenocista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtblPrenocista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblPrenocista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtPretragaPrenocistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPretragaPrenocistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPretragaPrenocistaActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblPrenocista;
    private javax.swing.JTextField jtxtPretragaPrenocista;
    // End of variables declaration//GEN-END:variables

    private void podesiTabelu() throws SQLException, Exception {
      
        Referent referent=(Referent) Sesion.getInstance().getMap().get("ulogovani");
        List<Prenociste> listaPrenocista=Controller.vratiListuPrenocistaZaOdredjenogReferenta(referent);
        
       
        pmp=new PrenocisteModelPrikaz(listaPrenocista);
        jtblPrenocista.setModel(pmp);
        prepareTableForSort();
        
        
        
    }
    private void prepareTableForSort() {
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(jtblPrenocista.getModel());
        jtblPrenocista.setRowSorter(rowSorter);
        
        
        jtxtPretragaPrenocista.getDocument().addDocumentListener(new DocumentListener() {
            
            
           
            
          
            
            
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
               
                if(jtblPrenocista.getRowCount()==0){
                    JOptionPane.showMessageDialog(null, "Ne postoji prenociste za zadati kriterijum");
                }
                String filterCity = jtxtPretragaPrenocista.getText();

                if (filterCity.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + filterCity));
                }
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                 if(jtblPrenocista.getRowCount()==0){
                    JOptionPane.showMessageDialog(null, "Ne postoji prenociste za zadati kriterijum");
                }
                String text = jtxtPretragaPrenocista.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }
}
