/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import controler.Controller;

import domen.Referent;
import domen.Student;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

import models.StudentModel;
import sesion.Sesion;

/**
 *
 * @author Stefan
 */
public class FPretraga extends javax.swing.JFrame{

    /**
     * Creates new form FPretraga
     */
    StudentModel sm;
    List<Student> studenti;
    public FPretraga() throws Exception {
        initComponents();
        setLocationRelativeTo(null);
        
       podesitabelu();
        
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        
        
        osluskuj();
    }
    public void podesitabelu() throws Exception{
        
        Referent referent=(Referent) Sesion.getInstance().getMap().get("ulogovani");
        
        
        studenti=Controller.VratiStudenteIzOdredjenogDoma(referent);
        
        
        sm=new StudentModel(studenti);
        jtblStudenti.setModel(sm);
        pripremiformu();
        prepareTableForSort();
        podesiSirinu();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtPretragaStudenta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblStudenti = new javax.swing.JTable();
        jbtnDetalji = new javax.swing.JButton();
        jbtnPrenociste1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pretraga Studenata");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretraga studenta po imenu"));

        jLabel1.setText("Unesite kriterijum za pretragu:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jtxtPretragaStudenta, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtPretragaStudenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jtblStudenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblStudenti);

        jbtnDetalji.setText("<html>\n<b>Detalji</b>\n</html>");
        jbtnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDetaljiActionPerformed(evt);
            }
        });

        jbtnPrenociste1.setText("<html>\nPrijava \n<br />\nPrenocista\n</html>");
        jbtnPrenociste1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrenociste1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnPrenociste1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(jbtnPrenociste1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDetaljiActionPerformed
      
        int  i=jtblStudenti.getSelectedRow();
        StudentModel sm=(StudentModel)jtblStudenti.getModel();
        List<Student> listaStudenata=sm.vratiStudente();
        
       Student s=sm.vratiStudente().get(i);
        
        try {
            JDialog detalji=new FNew(this, true,s);
            detalji.setVisible(true);
            podesitabelu();
            
        } catch (SQLException ex) {
            Logger.getLogger(FPretraga.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FPretraga.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbtnDetaljiActionPerformed

    private void jbtnPrenociste1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrenociste1ActionPerformed
        // TODO add your handling code here:
        int i=jtblStudenti.getSelectedRow();
        Student s=sm.vratiStudente().get(i);
        JFrame unos;
        try {
            unos = new FunosNovogPrenocista(s);
            unos.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FPretraga.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        dispose();
    }//GEN-LAST:event_jbtnPrenociste1ActionPerformed

  private void prepareTableForSort() {
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(jtblStudenti.getModel());
        jtblStudenti.setRowSorter(rowSorter);

        jtxtPretragaStudenta.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                sm=(StudentModel)jtblStudenti.getModel();
                
                 if(jtblStudenti.getRowCount()==0){
                    JOptionPane.showMessageDialog(null, "Ne postoji student za zadati kriterijum");
                }
                String filterCity = jtxtPretragaStudenta.getText();

                if (filterCity.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + filterCity));
                }
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                if(jtblStudenti.getRowCount()==0){
                    JOptionPane.showMessageDialog(null, "Ne postoji student za zadati kriterijum");
                }
                String text = jtxtPretragaStudenta.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDetalji;
    private javax.swing.JButton jbtnPrenociste1;
    private javax.swing.JTable jtblStudenti;
    private javax.swing.JTextField jtxtPretragaStudenta;
    // End of variables declaration//GEN-END:variables

    private void podesiSirinu() {
        jtblStudenti.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jtblStudenti.getColumnModel().getColumn(0).setPreferredWidth(70);
        jtblStudenti.getColumnModel().getColumn(1).setPreferredWidth(150);
        jtblStudenti.getColumnModel().getColumn(2).setPreferredWidth(150);
        jtblStudenti.getColumnModel().getColumn(3).setPreferredWidth(150);
        jtblStudenti.getColumnModel().getColumn(4).setPreferredWidth(100);
        jtblStudenti.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        
        
       //da vrednost teksta bude u centru
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jtblStudenti.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
    }

    private void osluskuj() {
        jtblStudenti.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
               jbtnDetalji.setVisible(true);
               jbtnPrenociste1.setVisible(true);
            }
        });
    }

    private void pripremiformu() {
        jbtnDetalji.setVisible(false);
        jbtnPrenociste1.setVisible(false);
    }

    
}

