 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import controler.Controller;

import domen.Grad;
import domen.Referent;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.xml.ws.Response;
import sesion.Sesion;
import transfer.interfejsi.Ulogovani;

/**
 *
 * @author Stefan
 */
public class Logovanje extends javax.swing.JFrame {

    /**
     * Creates new form Logovanje
     */
    public Logovanje() {
        initComponents();
        setLocationRelativeTo(null);

        jlblPokusaj.setText("Pokusaj 1 od 3");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtnPotvrdi = new javax.swing.JButton();
        jpasswordBrrk = new javax.swing.JPasswordField();
        jlblPokusaj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prijavljivanje Referenta");

        jLabel1.setText("Unesite broj vase radne knjizice");

        jbtnPotvrdi.setText("Potvrdi");
        jbtnPotvrdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPotvrdiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jpasswordBrrk, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnPotvrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(72, 72, 72))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblPokusaj, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(jpasswordBrrk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnPotvrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlblPokusaj, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int brojac = 1;

    private void jbtnPotvrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPotvrdiActionPerformed

        String text = new String(jpasswordBrrk.getPassword());

        if (brojac == 3) {
            JOptionPane.showMessageDialog(null, "Nemate vise pokusaja");
            System.exit(0);
        }
        try {

            List<Referent> referents = Controller.vratiSveReferente();

            for (Referent referent : referents) {

                if (text.equals(referent.getBrojRadneKnjizice())) {
                    Sesion.getInstance().getMap().put("ulogovani", referent);
                    JFrame glavna = new FGlavna();
                    
                    
                    
                    JOptionPane.showMessageDialog(null, "Uspesno ste ulogovani");
                    
                    
                    Referent ref = (Referent) Sesion.getInstance().getMap().get("ulogovani");
                    
                    
                  
                    

                  
                    
                    
                    
                    //****ispravka
                    Controller.dodajKlijenta(referent);
                    
                    
                    
                    glavna.setVisible(true);
                    this.setVisible(false);
                    dispose();
                }
            }

            if (this.isVisible()) {
                JOptionPane.showMessageDialog(null, "Greska: imate pravo jos " + (3 - brojac) + " pokusaja");
                jlblPokusaj.setText("Pokusaj " + (brojac + 1) + " od 3");
                brojac++;
            }

        } catch (SQLException e) {
            e.getMessage();
        } catch (Exception ex) {
            Logger.getLogger(Logovanje.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jbtnPotvrdiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logovanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logovanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logovanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logovanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {

                    FileInputStream fis = new FileInputStream("./server.config");
                    Properties properties = new Properties();
                    try {
                        properties.load(fis);
                        System.out.println("prvi");
                        //properties.getProperty("username")
                        System.out.println(properties.getProperty("port"));
                        
                        Socket socket = new Socket(properties.getProperty("ip"), Integer.parseInt(properties.getProperty("port")));
                        Sesion.getInstance().setSocket(socket);
                         new Logovanje().setVisible(true);
                    } catch (IOException ex) {
                        System.out.println("Nisu dobri parametri");
                       FConnectToServer fconecttt=new FConnectToServer();
                        fconecttt.setTitle("Unos novih parametara");
                        fconecttt.getJbtnSacuvaj().setVisible(false);
                        JOptionPane.showMessageDialog(null, "Parametri za konekciju sa serverom nisu odgovarajuci.\n Unesite nove.");
                        fconecttt.setVisible(true);
                    }
                   
                } catch (FileNotFoundException e) {
                   FConnectToServer fconnect = new FConnectToServer();
                    fconnect.getJbtnSacuvaj().setVisible(false);
                    fconnect.setVisible(true);
                    System.out.println("drugi");
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnPotvrdi;
    private javax.swing.JLabel jlblPokusaj;
    private javax.swing.JPasswordField jpasswordBrrk;
    // End of variables declaration//GEN-END:variables
}
